### ISSUE TITLE
error: relation "table_name" does not exist

### ISSUE THREAD

**Issue by olignyf** [mjhea0/express-testing-mocha-knex#3]
[frank@blackberry express-testing-mocha-knex]$ npx knex seed:run --env development
Using environment: development
error: relation "table_name" does not exist
    at Connection.parseE (/home/frank/express-testing-mocha-knex/node_modules/pg/lib/connection.js:601:11)
    at Connection.parseMessage (/home/frank/express-testing-mocha-knex/node_modules/pg/lib/connection.js:398:19)
    at Socket.<anonymous> (/home/frank/express-testing-mocha-knex/node_modules/pg/lib/connection.js:120:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by olignyf** [comment]
Solution is to edit the file 
src/server/db/seeds/users.js as mentionned on the blog post in section "Database Seed"
https://mherman.org/blog/testing-node-and-express/
